name: Benchmark Build

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"
    workflow_dispatch:

jobs:
    build-benchmark:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                version: ["0.15.1", "master"]
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps:
            - name: Install Neovim
              uses: jinzhongjia/neovim-action@v1.0.2
              with:
                  version: stable

            - name: Setup Zig
              uses: goto-bus-stop/setup-zig@v2
              with:
                  version: ${{ matrix.version }}

            - uses: actions/checkout@v4

            - name: Build benchmark
              run: zig build benchmark --summary all

            - name: Upload benchmark artifact
              uses: actions/upload-artifact@v4
              with:
                  name: benchmark-${{ matrix.os }}-zig-${{ matrix.version }}
                  path: |
                      zig-out/bin/benchmark*
                  retention-days: 7

