name: Format Check

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"
    workflow_dispatch:

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Zig
              uses: goto-bus-stop/setup-zig@v2
              with:
                  version: 0.15.1
            
            - uses: actions/checkout@v4
            
            - name: Check Zig code formatting
              run: zig fmt --check .

