name: Format Check

run-name: "Format Check 📝 [${{ github.event_name == 'pull_request' && format('PR #{0}', github.event.pull_request.number) || github.ref_name }}] by @${{ github.actor }}"

on:
    push:
        branches:
            - "*"
        paths:
            - "**.zig"
            - ".github/workflows/format-check.yml"
    pull_request:
        branches:
            - "*"
        paths:
            - "**.zig"
            - ".github/workflows/format-check.yml"
    workflow_dispatch:

jobs:
    format:
        name: "Check Zig code formatting"
        runs-on: ubuntu-latest
        steps:
            - name: Setup Zig
              uses: goto-bus-stop/setup-zig@v2
              with:
                  version: 0.15.1
            
            - uses: actions/checkout@v4
            
            - name: Check Zig code formatting
              run: zig fmt --check .
